# -------------------
# Data Input/Output
# -------------------
VisiumHD: True
on_disk:
  Cluster_resolution: 0.3
  Cluster_n_neighbors: 30
  max_memory_gb: 45
  qc_min_genes: 100 # Minimum number of genes expressed in a cell
  qc_min_cells: 10 # Minimum number of cells for a gene to be considered expressed

# Directory where your raw 10X data is stored
raw_data_dir: "/vol/research/brainTumorST/10X_Genomics_KD/"
# Directory to save RDS files
rds_data_dir: "/scratch/hh01116/10X_KD/KD_rds_data/" # otter12
# Directory to save processed data and results
project_dir: "/scratch/hh01116/10X_KD/" # otter12
# Prefix for the output files
output_file_prefix: "KD_3Runs_merged_no_noiseSpots"
# Names of the batch files (directories for VisiumHD, h5 files for standard Visium)
batch_file_h5_names: # for non-VisiumHD
batch_file_names:
  - "Run 1 - 22-08-24/118512-NM_bam"
  - "Run 1 - 22-08-24/118513-L1_bam"
  - "Run 1 - 22-08-24/118514R1_1_bam"
  - "Run 1 - 22-08-24/118515R1_4_bam"
  - "Run 2 - 11-10-24/118512L1_5" # very low total counts
  - "Run 2 - 11-10-24/118513R1_1" # very low total counts
  - "Run 2 - 11-10-24/118515L1_1"
  - "Run 2 - 11-10-24/121729NM_1"
  - "Run 3 - 14-11-24/118512-R13"
  - "Run 3 - 14-11-24/118513-NM2"
  - "Run 3 - 14-11-24/118514-NM4"
  - "Run 3 - 14-11-24/118515-NM4"
batch_names:
  - "Run1_SAL"    # total counts = 96501753
  - "Run1_KD"     # total counts = 54839364
  - "Run1_RAD"    # total counts = 78257855
  - "Run1_COMB"   # total counts = 105665564
  - "Run2_SAL"    # total counts = 11428641
  - "Run2_KD"     # total counts = 6727992
  - "Run2_COMB"   # total counts = 56695713
  - "Run2_RAD"    # total counts = 60861489
  - "Run3_SAL"    # total counts = 47166975
  - "Run3_KD"     # total counts = 42413396
  - "Run3_RAD"    # total counts = 60471126
  - "Run3_COMB"   # total counts = 45023077
inspect_replicates: # inspect the replicates in the same batch, using PCA plot
  - ["Run1_SAL", "Run2_SAL", "Run3_SAL"]
  - ["Run1_KD", "Run2_KD", "Run3_KD"]
  - ["Run1_RAD", "Run2_RAD", "Run3_RAD"]
  - ["Run1_COMB", "Run2_COMB", "Run3_COMB"]

# Script orders: 
# 1. 1_VisiumHD_read_merge_cluster.r
# 2. 2_visual_clusters
# 3. ./cellType/*
# cell type deconvolution, we specially focus on the cell2location method, but you can also use other methods like spatialXR, etc.
# please make sure the referencing dataset: ./rds_data/ref_GBM_scSeq.rds exists
spaceXR_ref_rds: "/vol/research/scratch1/NOBACKUP/hh01116/Jake_project/rds_data/GBM_earlyStage_scSeq_annotated_spacexr.rds"
cell2location_ref_h5ad: "/vol/research/scratch1/NOBACKUP/hh01116/10X_DIPG/cellType/gbm_analysis/reference_signatures/sc_ref.h5ad"
# 4. ./spatial_clustering/*
# for determining the spatial domain clusters, it's better to inspect it using `BayesSpace::qTune()` and `BayesSpace::qPlot()`
BayesSpace_k_clusters: 14
# 5. ./DGE/*
# There is DGE on the inferred cell type abundance in the above Step3. here, the first two steps are for the cluster level DGE analysis on the gene expression.
# below parameters will be used in the script
cluster_method: "seurat_clusters_no_noiseSpots"
Differential_Gene_Analysis:
  outTumour_cluster_nums: [1, 4, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
  inTumour_cluster_nums: [0]
  edgeTumour_cluster_nums: [2, 3]

  across_batch_comparisons: # the latter one is the control group
    - ["Run1_KD", "Run1_SAL"]
    - ["Run1_RAD", "Run1_SAL"]
    - ["Run1_COMB", "Run1_SAL"]
    - ["Run1_COMB", "Run1_RAD"]
    - ["Run2_KD", "Run2_SAL"]
    - ["Run2_RAD", "Run2_SAL"]
    - ["Run2_COMB", "Run2_SAL"]
    - ["Run2_COMB", "Run2_RAD"]
    - ["Run3_KD", "Run3_SAL"]
    - ["Run3_RAD", "Run3_SAL"]
    - ["Run3_COMB", "Run3_SAL"]
    - ["Run3_COMB", "Run3_RAD"]



# 6. [optional] ./TFA/*
# 7. [ignore] 3_wrap_analysis_to_Loupe.r
# we abandoned this script because Loupe file format is not open-source and we can't customize it much. Instead, we directly export the clustering results to the Cell Browser format below.


# 8. 3_cellbrowser_export_web.py
# 9. 4_generate_reports.py
# This script generates HTML reports for the analysis results. Report is under output/html_reports/index.html

# Output directory structure
output_dirs:
  
  # Core clustering outputs
  clustering: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/"
  clustering_umap_spatial: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/clusters_umap_spatial/"
  clustering_markers: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/markers/"
  clustering_spatialAware: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/spatial_aware_clustering/"
  
  # Cell type prediction outputs
  cell_type: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cell_type_prediction/"
  cell_type_spacexr: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cell_type_prediction/spaceXR_results/"
  cell_type_cell2loc: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cell_type_prediction/cell2location_results/"
  cell_type_deconv: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cell_type_prediction/deconvoluted_objects/"
  cell_type_viz: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cell_type_prediction/visualizations/"
  
  # Differential expression outputs
  deg: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/differential_expression/"
  deg_clusters: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/differential_expression/cluster_comparisons/"
  deg_celltypes: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/differential_expression/cell_type_comparisons/"
  deg_combine_celltypes: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/differential_expression/combine_cell_type_comparisons/"
  
  pathway_analysis_clusters: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/pathway_analysis_clusters/"
  pathway_analysis_clusters_plots: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/pathway_analysis_clusters/plots/"
  pathway_analysis_celltypes: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/pathway_analysis_celltypes/"
  pathway_analysis_celltypes_plots: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/pathway_analysis_celltypes/plots/"
  pathway_analysis_combine_celltypes: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/pathway_analysis_combine_celltypes/"
  pathway_analysis_combine_celltypes_plots: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/pathway_analysis_combine_celltypes/plots/"


  # Transcription factor activity outputs
  tfa: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/transcription_factor_activity/"
  tfa_activities: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/transcription_factor_activity/TF_activities/"
  tfa_features: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/transcription_factor_activity/feature_importance/"
  tfa_heatmaps: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/transcription_factor_activity/heatmaps/"
  
  # Manual labelling outputs
  manual_label: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/manual_labelling/"
  manual_counts: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/manual_labelling/exported_counts/"
  manual_assignments: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/manual_labelling/cluster_assignments/"
  manual_immune: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/manual_labelling/immune_analysis/"
  manual_markers: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/manual_labelling/marker_analysis/"
  
  # 10X Loupe browser files
  loupe: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/loupe_files/"




html_reports_dir: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/html_reports/"
# cellbrowser_html_output_dir: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/html_reports/cellbrowser"
# Cell Browser export settings
cellbrowser:
  # Cluster file paths for Cell Browser export, no need to prefix ./output/
  cluster_files:
    seurat_clusters_no_noiseSpots: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/seurat_clusters_no_noiseSpots.csv"
    banksy_cellTypes: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/banksy_cluster_cell2location.csv"
    banksy: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/banksy_cluster.csv" 
    BayesSpace: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/BayesSpace_cluster.csv"
    BayesSpace_cellTypes: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/clustering/BayesSpace_cluster_cell2location.csv"

  cellbrowser_dir: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cellbrowser_geneExpr"
  color_field: "banksy_cellTypes"
  label_field: "banksy_cellTypes"
  enum_fields: ["banksy_cellTypes", "banksy", "batch"]
  quick_genes: ["CD3", "CD4", "CD8a", "CD20", "CD11c", "HLA-DR", "CD68", "CD163", "P2Y12", "CD16", "CD14", "CD94", "MPO", "SOX2", "SOX9", "FOXP3", "CD117", "OLIG2", "PanCK", "PMEL", "CD31", "Claudin-5", "CD45", "MelanA", "Ki67", "CC3", "GFAP", "OX40L", "MMP9", "pERK", "pSTAT3", "HIF1a", "CD206", "CD39", "CD40", "CIRBP", "191Ir", "193Ir", "M-CSF-R", "GM-CSF-R", "PD-L1","PD-1", "CTLA-4", "Arg1", "IDO1", "Cd3e", "Nestin", "Olig1", "Sox11", "Pdgfra"]

  cell_abundances_dir: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cellbrowser_cellTypes"
  cell_abundances_csv: "/vol/research/scratch1/NOBACKUP/hh01116/10X_KD/KD_output/cell_type_prediction/cell2location_results/cell_abundances_and_clusters.csv"
  color_field_cell2location: "banksy_cellTypes"
  label_field_cell2location: "banksy_cellTypes" 
  enum_fields_cell2location: ["banksy_cellTypes", "batch"]


# -------------------
# Visualization
# -------------------
# Color map for clusters
color_map:
  "0": "#59BE86"
  "1": "#C798EE"
  "2": "#F56867"
  "3": "#FEB915"
  "4": "#7495D3"
  "5": "#D1D1D1"
  "6": "#6D1A9C"
  "7": "#15821E"
  "8": "#3A84E6"
  "9": "#997273"
  "10": "#787878"
  "11": "#DB4C6C"
  "12": "#9E7A7A"
  "13": "#554236"
  "14": "#AF5F3C"
  "15": "#93796C"
  "16": "#F9BD3F"
  "17": "#AAB370"
  "18": "#877F6C"
  "19": "#268785"
  "20": "#B2D8D8"
  "21": "#F9E4B7"
  "22": "#A020F0"
  "23": "#00FFFF"
  "24": "#800080"
  "25": "#4682B4"
  "26": "#D2691E"
  "27": "#008000"
  "28": "#90EE90"
  "29": "#FF69B4"
  "30": "#000080"
  "31": "#E6E6FA"
  "32": "#708090"
  "33": "#FA8072"
  "34": "#9370DB"
  "35": "#008B8B"
  "36": "#A9A9A9"
  "37": "#8FBC8F"
  "38": "#BC8F8F"
  "39": "#CD661D"
  "40": "#EEA2AD"
  "41": "#BDBDBD"
  "42": "#D8BFD8"
  "43": "#FFDAB9"
  "44": "#F0E68C"
  "45": "#B0E2FF"
  "46": "#7FFFD4"
  "47": "#F5DEB3"
  "48": "#6495ED"
  "49": "#DDA0DD"
  "50": "#98FB98"
  "51": "#F08080"
  "52": "#20B2AA"
  "53": "#778899"
  "54": "#7B68EE"
  "55": "#FF7F50"
  "56": "#66CDAA"
  "57": "#483D8B"
  "58": "#FFBEDA"
  "59": "#8B4513"
  "60": "#A0522D"
  "61": "#C71585"
  "62": "#DA70D6"
  "63": "#F0E6FA"
  "64": "#FF6347"
  "65": "#87CEFA"
  "66": "#708090"

