# Cell2location Analysis Configuration for GBM Dataset
# pred_cell2location_1_train_reference.py is only required for the first time you run the analysis.
# It trains the reference model and saves the signatures.
# After that, you can run pred_cell2location_2_map_spatial.py to map the spatial data.

# Input/Output Paths
paths:
  reference_output: '/vol/research/scratch1/NOBACKUP/hh01116/10X_DIPG/cellType/gbm_analysis/reference_signatures'
  reference_data: '/vol/research/scratch1/NOBACKUP/hh01116/10X_DIPG/cellType/gbm_analysis/reference_signatures/sc_ref.h5ad'
  spatial_data: 'KD_rds_data/KD_3Runs_merged_merged.h5ad'
  results_folder: 'cellType/gbm_analysis'
  spatial_output: 'cellType/gbm_analysis/cell2location_map'
  cell_abundance_results: 'KD_output/cell_type_prediction/cell2location_results'
  cell_abundance_heatmap_path: 'KD_output/cell_type_prediction/cell2location_results/cell_abundance_heatmap'
  nmf_models: 'KD_output/cell_type_prediction/cell2location_results/nmf_models'
  nmf_analysis_path: 'KD_output/cell_type_prediction/cell2location_results/nmf_analysis'
  dge_results_across_sample: 'KD_output/differential_expression/cell_type_comparisons/dge_results_across_sample'
  dge_results_within_sample: 'KD_output/differential_expression/cell_type_comparisons/dge_results_within_sample'
  dge_csv_combine: 'KD_output/differential_expression/cell_type_comparisons'
  dge_report: 'KD_output/html_reports/report_cellType_dge_presentations'
  cell_population_reports: 'KD_output/html_reports/report_cell_population'
  nmf_reports: 'KD_output/html_reports/report_nmf_analysis'
  # Output paths for combined cell type DGE results (used when combine_cell_types: true)
  dge_results_across_sample_combined: 'KD_output/differential_expression/combine_cell_type_comparisons/dge_results_across_sample'
  dge_results_within_sample_combined: 'KD_output/differential_expression/combine_cell_type_comparisons/dge_results_within_sample'
  dge_csv_combine_combined: 'KD_output/differential_expression/combine_cell_type_comparisons'


# Dataset Configuration
dataset:
  # Column names in reference data
  reference_batch_key: 'sampleID'
  reference_labels_key: 'sub_celltype'
  reference_covariate_keys: []
  
  # Column names in spatial data
  sample_batch_key: 'batch'
  
  # Dataset splitting parameters for multi-machine training
  splitting:
    enable_splitting: true  # Set to false to use original subsample behavior
    batch_size: 8000  # Number of cells per batch (should be <= max_cells)
    split_data_dir: 'cellType/gbm_analysis/split_datasets'  # Directory to save split datasets
    overlap_cells: 500  # Number of overlapping cells between batches (0 for no overlap)

# Shared Analysis Configuration
shared:
  
  # Selected cell types for visualization in the same spatial map during 2_map_spatial.py
  selected_cell_types: ['Effector.Memory.CD4.T', 'Naive.CD4.T', 'Stemlike.CD4.T', 'Regulatory.CD4.T', 'Lineage.neg.CD4.T']

  # Available cell types for analysis, can be found in adata.uns['mod']['factor_names']. Used during 4_DGE_after_deconv.py
  all_cell_types: ['Astrocytes', 'Astrocytes1', 'Astrocytes2', 'Astrocytes3', 'Astrocytes.Proliferating', 'Bcells', 'CAF', 'CAFs', 'DC', 'DC1', 'DC2', 'DC3', 'DC.Proliferating', 'Effector.&.Inhibitory.CD8.T', 'Effector.CD8.T', 'Effector.Memory.CD4.T', 'Effector.Memory.CD8.T', 'Endothelial', 'Gamma.delta.T', 'Immature.Oligo', 'Lineage.neg.CD4.T', 'MAST', 'MDM.Disease.Associated', 'MDM.Pro.Inflammatory', 'MDM.Proliferating', 'Mast', 'Mature.Oligo', 'Memory.CD8.T', 'Microglia.Disease.Associated', 'Microglia.Homeostatic', 'Microglia.Interferon.Responsive', 'Microglia.Proliferating', 'Monocytes', 'NK', 'NKT', 'Naive.CD4.T', 'Naive.CD8.T', 'Neuron1', 'Neuron2', 'Neutrophils', 'Oligodendrocyte', 'Plasma', 'Regulatory.CD4.T', 'Stemlike.CD4.T', 'Stemlike.CD8.T', 'T.Proliferating', 'Terminal.Effector.CD8.T', 'Tumor', 'pDC']
  
  # Whether to combine subtypes into new cell types for DGE
  combine_cell_types: true

  # Add cell type combinations for grouping subtypes
  cell_type_combinations:
    MDM: ['MDM.Disease.Associated', 'MDM.Pro.Inflammatory', 'MDM.Proliferating']
    Microglia: ['Microglia.Disease.Associated', 'Microglia.Homeostatic', 'Microglia.Interferon.Responsive', 'Microglia.Proliferating']
    CD4_T_cell: ['Effector.Memory.CD4.T', 'Naive.CD4.T', 'Stemlike.CD4.T', 'Regulatory.CD4.T', 'Lineage.neg.CD4.T']
    CD8_T_cell: ['Effector.&.Inhibitory.CD8.T', 'Effector.CD8.T', 'Terminal.Effector.CD8.T', 'Naive.CD8.T', 'Memory.CD8.T', 'Stemlike.CD8.T', 'Effector.Memory.CD8.T']
    Astrocytes: ['Astrocytes', 'Astrocytes1', 'Astrocytes2', 'Astrocytes3', 'Astrocytes.Proliferating']
    DC: ['DC', 'DC1', 'DC2', 'DC3', 'DC.Proliferating', 'pDC']
    Neurons: ['Neuron1', 'Neuron2']
    CAF: ['CAF', 'CAFs']

  # Target cell types for DGE analysis when not combining
  target_cell_types: ['Astrocytes', 'Astrocytes1', 'Astrocytes2', 'Astrocytes3', 'Astrocytes.Proliferating', 'Bcells', 'CAF', 'CAFs', 'DC', 'DC1', 'DC2', 'DC3', 'DC.Proliferating', 'Effector.&.Inhibitory.CD8.T', 'Effector.CD8.T', 'Effector.Memory.CD4.T', 'Effector.Memory.CD8.T', 'Endothelial', 'Gamma.delta.T', 'Immature.Oligo', 'Lineage.neg.CD4.T', 'MAST', 'MDM.Disease.Associated', 'MDM.Pro.Inflammatory', 'MDM.Proliferating', 'Mast', 'Mature.Oligo', 'Memory.CD8.T', 'Microglia.Disease.Associated', 'Microglia.Homeostatic', 'Microglia.Interferon.Responsive', 'Microglia.Proliferating', 'Monocytes', 'NK', 'NKT', 'Naive.CD4.T', 'Naive.CD8.T', 'Neuron1', 'Neuron2', 'Neutrophils', 'Oligodendrocyte', 'Plasma', 'Regulatory.CD4.T', 'Stemlike.CD4.T', 'Stemlike.CD8.T', 'T.Proliferating', 'Terminal.Effector.CD8.T', 'Tumor', 'pDC']

  # Quantile settings
  quantiles:
    abundance_threshold: 0.75
    low_quantile: 0.25
    high_quantile: 0.75
    vmax_quantile: 0.992  # p99.2
  
  # Image and presentation settings
  image_settings:
    dpi: 300
    format: "png"
    spot_size: 30
    

# Gene Filtering Parameters (Reference Data)
gene_filtering:
  cell_count_cutoff: 5  # Keep markers of rare cell types (recommended: 5)
  cell_percentage_cutoff2: 0.05  # Increased from tutorial 0.03 for more stringent filtering
  nonz_mean_cutoff: 1.2  # Increased from tutorial 1.12 for 8k-16k genes selection

# Reference Model Training Parameters
reference_model:
  max_epochs: 300  # Increased from tutorial 250 to ensure convergence
  batch_size: 2500  # Large batch size as recommended
  train_size: 1.0  # Use all data
  num_samples: 1000  # For posterior sampling
  accelerator: 'gpu'
  device: 1

# Cell2location Model Parameters
cell2location:
  # CRITICAL: Adjust N_cells_per_location based on your tissue type
  # Estimate from paired histology images (tutorial uses 30 as example)
  N_cells_per_location: 25  # Adjusted for GBM tissue (lower than lymph node)
  
  # CRITICAL: Test both values - use 20 for high technical variability, 200 for low
  detection_alpha: 20  # Start with 20 for human tissue (recommended)
  
  # Training parameters
  max_epochs: 10000  # Increased from tutorial 30000
  batch_size: null # use full data (recommended and it's highest accuracy)
  train_size: 1.0 # Size of training set in the range [0.0, 1.0]. Use all data points in training because we need to estimate cell abundance at all locations.
  num_samples: 1000
  accelerator: 'gpu'
  device: 1
  
  # Alternative detection_alpha to test
  detection_alpha_alternative: 200

# Clustering Analysis Parameters
clustering:
  n_neighbors: 15  # KNN neighbors for clustering
  leiden_resolution: 1.1  # Leiden clustering resolution
  umap_min_dist: 0.3
  umap_spread: 1.0

# DGE Analysis Parameters
dge_analysis:
  n_top_genes_per_group: 1000 # Number of top DEGs to identify per comparison
  use_raw_counts_cell_type_dge: false # Use adata.raw for DGE by cell type abundance
  use_raw_counts_nmf_dge: false # Use adata.raw for DGE by NMF groups

# NMF Colocalization Analysis Parameters
nmf_analysis:
  # CRITICAL: Tutorial recommends range 5-30
  # small factor number: find a few most distinct cellular compartments
  # large factor number: find very strong co-location signal and assume that most cell types don't co-locate (>30)
  n_fact_range: [10, 35, 2] # [start, end, step]
  n_restarts: 3  # Number of training restarts
  alpha: 0.01  # NMF regularization
  init: 'random'
  tol: 0.000001  # Convergence tolerance
  chosen_n_factors_for_dge: 5 # Number of NMF factors to use for DGE

# Visualization Parameters
visualization:
  figure_size: [15, 10]
  ncols: 4
  spot_size: 1.3
  colormap: 'magma'
  max_cell_types_to_plot: 30

# Quality Control Parameters
quality_control:
  plot_history_skip_epochs: 20  # Skip first N epochs in training plots
  spatial_history_skip_epochs: 1000  # Skip first N epochs for spatial model

# Advanced Parameters
advanced:
  # For cell-type specific expression computation (memory intensive)
  compute_cell_type_expression: false  # Set to true if you have enough RAM
  
  # Posterior sampling parameters
  posterior_quantiles: [0.05, 0.5, 0.95]  # Quantiles to compute
  
  # Memory optimization
  use_quantiles_only: false  # Set to true to save memory on large datasets

# Local Report Generation
local_report:

  # Cell population presentation slide settings
  cell_population:
    # keywords from adata.uns['mod']['factor_names']
    cell_types_for_population: ['Effector.&.Inhibitory.CD8.T', 'Effector.CD8.T', 'Terminal.Effector.CD8.T', 'Naive.CD8.T', 'Memory.CD8.T', 'Stemlike.CD8.T', 'Effector.Memory.CD8.T', 'Effector.Memory.CD4.T', 'Naive.CD4.T', 'Stemlike.CD4.T', 'Regulatory.CD4.T', 'Lineage.neg.CD4.T']
    slide_title_prefix: "Cell Population under Sample"
    selected_pdf_pattern: "{output_dir}/{batch}_selected_cell_types.pdf"
    all_cell_abundance_pdf_pattern: "{output_dir}/{batch}_cell_abundance_all.pdf"
    layout_rows: 2
    layout_cols: 3

  # NMF analysis presentation settings
  nmf_analysis:
    # Heatmap settings
    heatmap:
      slide_title_prefix: "NMF Analysis Heatmap"
      pdf_pattern: "{output_dir}/{batch}_nmf_analysis_heatmap.pdf"
      layout_rows: 3
      layout_cols: 2
    
    # Spatial density plot settings
    spatial_density:
      slide_title_prefix: "NMF Analysis Spatial Density"
      pdf_pattern: "{output_dir}/{batch}_nmf_analysis_spatial_density.pdf"
      layout_rows: 3
      layout_cols: 2

